config/routes.rb
Shortstack::Application.routes.draw do
  root 'pages#home'

  resources :merchants, only: [:show]

  get '/search', to: 'search#index'
  get '/auth/:provider/callback', to: 'sessions#create'
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  def show
    @merchant = DELIVERY_CLIENT.info(params[:id])
    @menu = DELIVERY_CLIENT.menu(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @search = DELIVERY_CLIENT.search params[:q]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path, notice: 'Signed in!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Short Stack</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>

  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lato' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/merchants/show.html.erb
<div class='merchant'>
  <h1><%= @merchant.merchant.summary.name %></h1>

  <% @menu.menu.each do |m| %>
    <h2><%= m.name %></h2>
  <% end %>
</div>

app/views/pages/home.html.erb
<%= form_tag search_path, method: 'get' do %>
  <%= text_field_tag :q, nil, placeholder: '199 Water St 10038' %>
<% end %>

app/views/search/index.html.erb
<% @search.merchants.each do |m| %>
  <div class='merchant'>
    <%= link_to merchant_path(m.id) do %>
      <h3><%= m.summary.name %></h3>
    <% end %>

    <% if m.summary.cuisines %>
      <p><%= m.summary.cuisines.join(', ') %></p>
    <% end %>

    <p><%= m.summary.description %></p>
  </div>
<% end %>